name: 'Karrotmini Site Deployment'
description: 'Deployment GitHub Actions to karrotmini-site'
inputs:
  api-key:
    description: 'API Key'
    required: true
  build-output-directory:
    description: 'The build output directory of where to zip.'
    required: true
  preview-id:
    description: 'Unique preview id for the deployment'
    required: true
outputs:
  site-url:
    description: "Public accessable site preview url"
    value: ${{ steps.zip-and-upload.outputs.site-url }}
  karrot-deeplink-url:
    description: "Deeplink URL via karrotmarket application"
    value: ${{ steps.zip-and-upload.outputs.karrot-deeplink-url }}
runs:
  using: "composite"
  steps:
    - id: zip-and-upload
      name: Zip and Upload
      run: |
        ARCHIVE_FILE_PATH=$(mktemp -d)/${{ inputs.build-output-directory }}.zip
        zip -r $ARCHIVE_FILE_PATH ${{ inputs.build-output-directory }}
        RESULT=$(curl --location --request POST \
          'https://mini.kr.karrotmarket.com/console/miniapps/bundle/upload-preview' \
          --header 'X-Api-Key: ${{ inputs.api-key }}' \
          --form "file=@$ARCHIVE_FILE_PATH" \
          --form 'preview_id="${{ inputs.preview-id }}"')
        echo $RESULT
        echo "site-url=$(echo $RESULT | jq --raw-output .site_url)" >> $GITHUB_OUTPUT
        echo "karrot-deeplink-url=$(echo $RESULT | jq --raw-output .karrot_deeplink_url)" >> $GITHUB_OUTPUT
      shell: bash

    - uses: actions/github-script@v6
      id: encoded-karrot-deeplink-url
      with:
        script: return encodeURIComponent("${{ steps.zip-and-upload.outputs.karrot-deeplink-url }}");
        result-encoding: string

    - name: Find Comment
      if: ${{ github.event_name == 'pull_request' }}
      uses: peter-evans/find-comment@v2
      id: fc
      with:
        issue-number: ${{ github.event.pull_request.number }}
        comment-author: 'github-actions[bot]'
        body-includes: karrotmini deployment result

    - name: Upsert Result
      if: ${{ github.event_name == 'pull_request' }}
      uses: peter-evans/create-or-update-comment@v2
      with:
        comment-id: ${{ steps.fc.outputs.comment-id }}
        issue-number: ${{ github.event.pull_request.number }}
        body: |
          ## karrotmini deployment result

          ${{ steps.zip-and-upload.outputs.site-url }}
          ${{ steps.zip-and-upload.outputs.karrot-deeplink-url }}
          <img src="https://api.qrcode-monkey.com//qr/custom?download=false&file=svg&data=${{ steps.encoded-karrot-deeplink-url.outputs.result }}&size=550" />
        edit-mode: replace
