name: 'Karrotmini Site Deployment'
description: 'Deployment GitHub Actions to karrotmini-site'
inputs:
  api-key:
    description: 'API Key'
    required: true
  build-output-directory:
    description: 'The build output directory of where to zip.'
    required: true
  preview-id:
    description: 'Unique preview id for the deployment'
    required: true

outputs:
  site-url:
    description: "OUTPUT 1"
    value: ${{ steps.zip-and-upload.outputs.site-url }}
  karrot-deeplink-url:
    description: "OUTPUT 2"
    value: ${{ steps.zip-and-upload.outputs.karrot-deeplink-url }}
runs:
  using: "composite"
  steps:
    - id: zip-and-upload
      name: Zip and Upload
      run: |
        ARCHIVE_FILE_PATH=$(mktemp -d)/${{ inputs.build-output-directory }}.zip
        zip -r $ARCHIVE_FILE_PATH ${{ inputs.build-output-directory }}
        RESULT=$(curl --location --request POST \
          'https://mini.kr.karrotmarket.com/console/miniapps/bundle/upload-preview' \
          --header 'X-Api-Key: ${{ inputs.api-key }}' \
          --form "file=@$ARCHIVE_FILE_PATH" \
          --form 'preview_id="${{ inputs.preview-id }}"')
        echo $RESULT
        echo "site-url=$(echo $RESULT | jq --raw-output .site_url)" >> $GITHUB_OUTPUT
        echo "karrot-deeplink-url=$(echo $RESULT | jq --raw-output .karrot_deeplink_url)" >> $GITHUB_OUTPUT
      shell: bash

    - name: Find Comment
      if: ${{ github.event_name == 'pull_request' }}
      uses: peter-evans/find-comment@v2
      id: fc
      with:
        issue-number: ${{ github.event.pull_request.number }}
        comment-author: 'github-actions[bot]'
        body-includes: karrotmini deployment result

    - uses: kentaro-m/qr-code-commenter-action@v0.1.2
      if: steps.fc.outputs.comment-id == ''
      with:
        repo-token: ${{ github.token }}
        content: ${{ steps.zip-and-upload.outputs.karrot-deeplink-url }}
        comment: |
          karrotmini deployment result

          ${{ steps.zip-and-upload.outputs.site-url }}
          Scan a code with your device.
          {qrcode}
