name: 'Karrotmini Site Deployment'
description: 'Deployment GitHub Actions to karrotmini-site'
inputs:
  api-key:
    description: 'API Key'
    required: true
  build-output-directory:
    description: 'The build output directory of where to zip'
    required: true
  preview-id:
    description: 'Unique preview id for the deployment'
    required: true
  bundle-upload-http-endpoint:
    description: 'The HTTP endpoint to upload the bundle to'
    required: false
    default: 'https://mini.kr.karrotmarket.com/console/miniapps/bundle/upload-preview'
outputs:
  site-url:
    description: "Public accessable site preview url"
    value: ${{ steps.upload.outputs.site-url }}
  karrot-deeplink-url:
    description: "Deeplink URL via karrotmarket application"
    value: ${{ steps.upload.outputs.karrot-deeplink-url }}
runs:
  using: "composite"
  steps:
    - id: archive-file-path
      run: |
        echo "result=$(mktemp -d)/Archive.zip" >> $GITHUB_OUTPUT
      shell: bash

    - name: Zip build output
      run: |
        zip -r $ARCHIVE_FILE_PATH ./
      shell: bash
      working-directory: ${{ inputs.build-output-directory }}
      env:
        ARCHIVE_FILE_PATH: ${{ steps.archive-file-path.outputs.result }}

    - id: upload
      name: Upload archived build output
      run: |
        RESULT=$(curl --silent --location --request POST \
          '${{ inputs.bundle-upload-http-endpoint }}' \
          --header 'X-Api-Key: ${{ inputs.api-key }}' \
          --form "file=@$ARCHIVE_FILE_PATH" \
          --form 'preview_id="${{ inputs.preview-id }}"')
        echo $RESULT

        if [ $(echo $RESULT | jq empty > /dev/null 2>&1; echo $?) -ne 0 ]; then
          echo "failure-message=$RESULT" >> $GITHUB_OUTPUT
          exit 1
        fi

        if [ $(echo $RESULT | jq 'has("site_url") and has("karrot_deeplink_url")') = false ]; then
          if [ $(echo $RESULT | jq 'has("message")') = true ]; then
            echo "failure-message=$(echo $RESULT | jq -e --raw-output .message)" >> $GITHUB_OUTPUT
          else
            echo "failure-message=" >> $GITHUB_OUTPUT
          fi
          exit 1
        fi

        echo "site-url=$(echo $RESULT | jq -e --raw-output .site_url)" >> $GITHUB_OUTPUT
        echo "karrot-deeplink-url=$(echo $RESULT | jq -e --raw-output .karrot_deeplink_url)" >> $GITHUB_OUTPUT
        echo "miniapp-id=$(echo $RESULT | jq -e --raw-output .miniapp.id)" >> $GITHUB_OUTPUT
        echo "miniapp-name=$(echo $RESULT | jq -e --raw-output .miniapp.name)" >> $GITHUB_OUTPUT
      shell: bash
      env:
        ARCHIVE_FILE_PATH: ${{ steps.archive-file-path.outputs.result }}

    - uses: actions/github-script@v6
      id: encoded-karrot-deeplink-url
      with:
        script: return encodeURIComponent("${{ steps.upload.outputs.karrot-deeplink-url }}");
        result-encoding: string

    - name: Find Comment
      if: ${{ github.event_name == 'pull_request' && always() }}
      uses: peter-evans/find-comment@v2
      id: fc
      with:
        issue-number: ${{ github.event.pull_request.number }}
        comment-author: 'github-actions[bot]'
        body-includes: '[${{ steps.upload.outputs.miniapp-name }}] karrotmini deployment result'

    - name: Upsert Result (Success)
      if: ${{ github.event_name == 'pull_request' && success() }}
      uses: peter-evans/create-or-update-comment@v2
      with:
        comment-id: ${{ steps.fc.outputs.comment-id }}
        issue-number: ${{ github.event.pull_request.number }}
        body: |
          ## [${{ steps.upload.outputs.miniapp-name }}] karrotmini deployment result

          Preview Site URL: ${{ steps.upload.outputs.site-url }}

          <!-- See https://www.qrcode-monkey.com/qr-code-api-with-logo/ -->
          Open Preview site on 당근마켓. Scan a code with your device!
          <img src="https://api.qrcode-monkey.com/qr/custom?download=false&file=svg&data=${{ steps.encoded-karrot-deeplink-url.outputs.result }}&config=%7B%22logo%22%3A%22e57fa33bd90ef3e110ef7d6ca5e10f9139ef311b.png%22%7D" />
        edit-mode: replace

    - name: Upsert Result (Failure)
      if: ${{ github.event_name == 'pull_request' && failure() }}
      uses: peter-evans/create-or-update-comment@v2
      with:
        comment-id: ${{ steps.fc.outputs.comment-id }}
        issue-number: ${{ github.event.pull_request.number }}
        body: |
          ## karrotmini deployment result

          Preview Site 배포에 실패했어요 😢 ${{ steps.upload.outputs.failure-message }}
        edit-mode: replace
